# This file was generated by GoReleaser. DO NOT EDIT.
cask "talaria" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "6a5f95a005d7aeba6c3c7547a69a7e797e7082b834f33458c9c04d6679ff24fd"
      url "https://github.com/BAAX-Business-Development/homebrew-talaria/releases/download/v#{version}/talaria_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "73d39085626e95611dc10906238162d9f5545955b82175fcf52f37df5362447d"
      url "https://github.com/BAAX-Business-Development/homebrew-talaria/releases/download/v#{version}/talaria_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e61bb1409de0127cf4a63341df02469a010decb25953ed7022ff94d9299c2709"
      url "https://github.com/BAAX-Business-Development/homebrew-talaria/releases/download/v#{version}/talaria_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9b6aa55dd66affb9eb46483fe37796b898f271057f2efcb76b94c3204ef31bf"
      url "https://github.com/BAAX-Business-Development/homebrew-talaria/releases/download/v#{version}/talaria_#{version}_linux_amd64.tar.gz"
    end
  end

  name "talaria"
  desc "Build and deploy a Talaria app as a package."
  homepage "https://github.com/BAAX-Business-Development/Talaria"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "talaria"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/talaria"]
    end
  end

  # No zap stanza required
end
