# This file was generated by GoReleaser. DO NOT EDIT.
cask "talaria" do
  version "0.14.1"

  on_macos do
    on_arm do
      sha256 "6d7f9cbe5b93f08966b9aeb8458fb64017f636c9d252de79d7e60a7ec5c74036"
      url "https://github.com/BAAX-Business-Development/homebrew-talaria/releases/download/v#{version}/talaria_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0210e17be2ac2f1e41b94dc935c1e4ac6eae8035907de6d23779650b48c5e215"
      url "https://github.com/BAAX-Business-Development/homebrew-talaria/releases/download/v#{version}/talaria_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "29e8f0328804617693182d47ce68634e871da03bf8f640e73db53a436d38eb20"
      url "https://github.com/BAAX-Business-Development/homebrew-talaria/releases/download/v#{version}/talaria_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4ea66107b47f5a2a992ed752bab31ac17b0fa6603a8c5d9bd62093cdde8a8cb5"
      url "https://github.com/BAAX-Business-Development/homebrew-talaria/releases/download/v#{version}/talaria_#{version}_linux_amd64.tar.gz"
    end
  end

  name "talaria"
  desc "Build and deploy a Talaria app as a package."
  homepage "https://github.com/BAAX-Business-Development/Talaria"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "talaria"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/talaria"]
    end
  end

  # No zap stanza required
end
