# This file was generated by GoReleaser. DO NOT EDIT.
cask "talaria" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "2d3c8de114057c1735c732bdaa6ae04143a815c24a29e678951db4b4b9037488"
      url "https://github.com/BAAX-Business-Development/homebrew-talaria/releases/download/v#{version}/talaria_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "03c73578b6c386702c201a77f968869336cd7021432a2a281e993b17140b3ed7"
      url "https://github.com/BAAX-Business-Development/homebrew-talaria/releases/download/v#{version}/talaria_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d68fe9e708cae62c07c83647cb31a3d5e7576a4eb296d9d16f7422c5d9fbf50e"
      url "https://github.com/BAAX-Business-Development/homebrew-talaria/releases/download/v#{version}/talaria_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a0e7971467f216e58a86c9e20719c50ee688a6b69debdf918bf7f6c9b3257bf8"
      url "https://github.com/BAAX-Business-Development/homebrew-talaria/releases/download/v#{version}/talaria_#{version}_linux_amd64.tar.gz"
    end
  end

  name "talaria"
  desc "Build and deploy a Talaria app as a package."
  homepage "https://github.com/BAAX-Business-Development/Talaria"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "talaria"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/talaria"]
    end
  end

  # No zap stanza required
end
